replicas: 2
image:
  repository: my-gateway-image
  tag: staging
resources:
  limits:
    cpu: "1000m"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"
service:
  type: LoadBalancer  # External access for staging
  port: 80
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75