replicas: 1
image:
  repository: my-gateway-image
  tag: latest
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
service:
  type: LoadBalancer  # Change to LoadBalancer or NodePort
  port: 80
  # If using NodePort, specify nodePort
  # nodePort: 30000-32767
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75