gateway:
  namespace: vifunction-ns
  image: docker.io/quangnguyen2017/vifunction-gateway:latest
  service:
    type: NodePort
    port: 8080
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
  replicas: 1
  config:
    key1: value
    key2: value
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilizationPercentage: 80
    targetRamUtilizationPercentage: 80
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: minikube.local
        paths:
          - path: /gateway
            pathType: Prefix
    tls: []

dataservice:
  namespace: vifunction-ns
  image: docker.io/quangnguyen2017/vifunction-dataservice:latest
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
  replicas: 1
  config:
    key1: value
    key2: value
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilizationPercentage: 80
    targetRamUtilizationPercentage: 80
  ingress:
    enabled: false

imagebuilder:
  namespace: vifunction-ns
  image: docker.io/quangnguyen2017/vifunction-imagebuilder:latest
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
  replicas: 1
  config:
    key1: value
    key2: value
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilizationPercentage: 80
    targetRamUtilizationPercentage: 80
  ingress:
    enabled: false
