# Use the official Golang image to build the app
FROM golang:1.23 AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the go.mod and go.sum files first
COPY go.mod ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o functions-deployer .

# Start a new stage from scratch
FROM alpine:latest

# Set the Current Working Directory inside the container
WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/functions-deployer .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the executable
CMD ["./functions-deployer"]

# podman build -t functions-deployer .
# podman run -p 8080:8080 functions-deployer