# Use debian:bullseye-slim as the base image
FROM debian:bullseye-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install dependencies required for Python and Buildah
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Buildah and CA certificates
RUN apt-get update && \
    apt-get install -y buildah ca-certificates && \
    update-ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install Flask
RUN pip3 install --no-cache-dir Flask

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]