replicaCount: 1

image:
  repository: docker.io/quangnguyen2017/giongfunctions-kernel-images-builder
  tag: latest

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "400m"
    memory: "512Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80