namespace: giong-functions

replicaCount: 1

image:
  repository: quangnguyen2017/kernel-images-builder
  tag: latest

service:
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "400m"
    memory: "512Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Ingress configuration
ingress:
  enabled: false