apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataservice.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dataservice.name" . }}
    helm.sh/chart: {{ include "dataservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default "" }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "dataservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}