apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataservice.fullname" . }}
  namespace: vifunction-controller
  labels:
    {{- include "dataservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "dataservice.selectorLabels" . | nindent 4 }}