replicas: 1
image:
  repository: my-image-builder
  tag: latest
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
service:
  type: ClusterIP
  port: 8080
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80