name: Build and Push images to GCR

on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

env:
  DOCKER_HUB_USERNAME: lieusolocode

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push vifunction-store
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.Store
          file: ./src/ViFunction.Store/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/vifunction-store:latest

      - name: Build and push vifunction-gateway
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.Gateway
          file: ./src/ViFunction.Gateway/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/vifunction-gateway:latest

      - name: Build and push vifunction-imagebuilder
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.ImageBuilder
          file: ./src/ViFunction.ImageBuilder/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/vifunction-imagebuilder:latest

      - name: Build and push vifunction-kubeops
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.KubeOps
          file: ./src/ViFunction.KubeOps/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/vifunction-kubeops:latest

      - name: Build and push vifunction-edgerouter
        uses: docker/build-push-action@v3
        with:
          context: ./src/ViFunction.EdgeRouter
          file: ./src/ViFunction.EdgeRouter/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/vifunction-edgerouter:latest
