{{- define "sharedlib.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  namespace: {{ .namespace }}
data:
  {{- range $key, $value := .config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}