apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}-deploy
  namespace: {{ namespace }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      containers:
        - name: {{ name }}
          image: {{ image }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "{{ memory_request }}"
              cpu: "{{ cpu_request }}"
            limits:
              memory: "{{ memory_limit }}"
              cpu: "{{ cpu_limit }}"